### ISSUE TITLE
user balance not updating upon performing P2P

### ISSUE THREAD

**Issue by Ibar000** [SenitCorp/bugtracker#39]
![image from ios 3](https://user-images.githubusercontent.com/22422309/43663529-76bd47b0-972f-11e8-9c55-683171f07f61.jpg)

[Karsten]
Now the P2P shows up in his balance but the first send does not; he should have 40 GBP.

![image from ios 4](https://user-images.githubusercontent.com/22422309/43663864-8e41d18e-9730-11e8-9bce-6c92a44f2256.jpg)

**Comment by qatester1234** [comment]
Fixed #39

**Comment by jayrulez** [comment]
We need to test this further to ensure that it does not still happen.

**Comment by jayrulez** [comment]
I will close this if no one else has experienced this in testing.
